[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "CoinFut"
  [en.params]
    tagline = "Specializing in cryptocurrency learning and practice, sharing personal insights."

[zh-CN]
  languageName = "中文"
  languageCode = "zh-CN"
  weight = 1
  title = "币见未来"
  [zh-CN.params]
    tagline = "专注于加密货币学习与实践，分享个人心得。"
