[en]
  languageName = "English"
  languageCode = "en"
  weight = 2
  title = "CoinFut"
  [en.params]
    tagline = "A text-focused blog theme"

[zh-CN]
  languageName = "中文"
  languageCode = "zh-CN"
  weight = 1
  title = "币见未来"
  [zh-CN.params]
    tagline = "一个专注于文本的博客主题"
